application: app-name
version: 1
runtime: python
api_version: 1

inbound_services:
- xmpp_message

handlers:
- url: /_ah/xmpp/message/chat/
  script: main.py

- url: /data
  script: main2.py
